#! /bin/sh

# Exit immediately if a command exits with a non-zero status
set -e

echo "Setting up eth0"
ip addr add 42.42.42.1/24 dev eth0
ip link set eth0 up

echo "Setting up the vxlan - static"
ip link add vxlan10 type vxlan id 10 remote 42.42.42.2 dstport 4789 dev eth0
ip link set vxlan10 up

echo "Up eth1"
ip link set eth1 up

echo "Creating the bridge"
ip link add br0 type bridge

echo "Up bridge"
ip link set br0 up

echo "Adding interfaces to the bridge"
ip link set eth1 master br0
ip link set vxlan10 master br0

echo "Adding address to the bridge"
ip addr add 30.1.1.3/24 dev br0

echo "Configuration completed successfully"
exit 0
